deis/workflow

- src/managing-deis/platform-monitoring.md
* adds link to the deis/monitor repo
> docs(monitoring): Update the platform monitoring section

- src/understanding-deis/architecture.md
Updates the description of the router mesh-- etcd language out; k8s language in.
> doc(arhcitecture): Update router mesh description

- .gitignore
- src/installing-deis/quickstart.md
- src/managing-deis/platform-logging.md
I am still tweaking the docs some but thought I would go ahead and submit the PR.
fixes deis/logger#38
> docs(logging): Add documentation about platform logging

- src/installing-deis/quickstart.md
- src/installing-deis/system-requirements.md
* Include version recommendation for Kubernetes
* Include version recommendation for Docker daemon
* Document insecure registry requirement
> Consolidate system and configuration requirements into one spot.

- mkdocs.yml
- src/index.md
- src/installing-deis/installing-deis-workflow.md
- src/installing-deis/quickstart.md
- src/reference-guide/terms.md
Doing this piecemeal rather than all at once. Refs deis/docs-v2#7
> Start massaging Workflow into docs

- src/managing-deis/platform-ssl.md
closes #25 
pinging @krancour for review as he knows this field better than I do
> feat(managing_deis): add platform SSL documentation

- Dockerfile
- Makefile
- README.md
We're just docs now!
Add `Makefile` targets for docker-based and local documentation options.
Fixes #27
> Update README and interactive Docker serve

- src/understanding-deis/concepts.md
Will do other sections in separate PRs.
Fixes #6
> Rework concepts section

- src/understanding-deis/components.md
> Update Components documentation for v2

- src/using-deis/configuring-an-application.md
Brings this in line with the current behavior, fixes #55
/cc @helgi
> Update application health check documentation to match reality

- requirements.txt
Minor bug fixes. See https://github.com/mkdocs/mkdocs/compare/0.15.2...0.15.3
> chore(requirements): update mkdocs to 0.15.3

- mkdocs.yml
- src/managing-workflow/adding-or-removing-hosts.md
> docs(managing-workflow): Remove add/remove host docs

- mkdocs.yml
- src/managing-workflow/backing-up-and-restoring-data.md
- src/understanding-workflow/components.md
> doc(backup/restore): Remove backup/restore doc placeholder

- CONTRIBUTING.md
- Makefile
- README.md
- src/contributing/development-environment.md
- src/contributing/overview.md
- src/contributing/submitting-a-pull-request.md
- src/understanding-workflow/components.md
- themes/deis/base.html
This PR contains a number of updates to account for docs, tests, components, etc... things that are moving, will move, or have moved and weren't already accounted for.
> chore(*): Update links for things that have or are moving

- CONTRIBUTING.md
- src/contributing/maintainers.md
- src/contributing/overview.md
- src/roadmap/planning-process.md
> doc(*): Replace references to IRC/Freenode with Slack

- src/installing-workflow/configuring-object-storage.md
Fixes #97 
Requires https://github.com/deis/controller/pull/523
> doc(README.md): add documentation on configuring the controller for object storage

- src/installing-workflow/configuring-object-storage.md
also fix up dead links to the deis-dev chart
closes #95
> docs(installing-deis): add docs on database config

- README.md
> doc(README.md): update readme to reflect beta status

- src/installing-workflow/configuring-object-storage.md
> doc(object-storage): add note on beta status

- src/installing-workflow/configuring-object-storage.md
Fixes https://github.com/deis/workflow/issues/101
> doc(object-storage): add sections on configuring secrets for the helm chart

- src/installing-workflow/configuring-object-storage.md
It is general enough to apply to all components
> doc(object-storage): move the GCS section to a more global area

- README.md
This patch makes the readme more consistent with readmes in other Deis component repos
> fix(README.md): move the about section to below the beta text

- src/installing-workflow/configuring-object-storage.md
and modify wording and location on slugrunner’s note
Fixes #109
> doc(object-storage): add note about slugbuilder standalone component

- src/installing-workflow/configuring-object-storage.md
> doc(README.md): fix grammar and add clarity

- src/managing-workflow/platform-logging.md
> fix(logging): Remove the term minion from platform-logging

- src/managing-workflow/configuring-load-balancers.md
> doc(load balancer): Expand detail on manual LB configuration

- README.md
> doc(README.md): add links and descriptions for each component

- src/managing-workflow/platform-logging.md
Change examples for installing deis-logger to reflect recent workflow to controller changes.
> chore(platform loggging): Change workflow to controller

- src/installing-workflow/configuring-object-storage.md
change docs to use deis-object-storage-secret for configuring the storage for the builder, slugbuilder , controller and slugrunner.
> feat(storage): change docs to use deis-object-storage-secret for configuring the storage

- Makefile
- _scripts/gutenbuild
Few things that I found while automating consolidated doc and deis.com builds
via `deis/gutenberg`.
Tested all existing "apis" via `make`, so this should be mergeable as-is.
Additional PRs to follow as docs consolidation progresses!
> Cleanups and adapters for documentation consolidation.

- src/using-workflow/configuring-an-application.md
> feat(healthchecks): improve healthcheck documentation, add new options and include defaults

- src/installing-workflow/configuring-object-storage.md
> feat(storage): change docs to use deis-object-storage-secret for configuring database

- CONTRIBUTING.md
> fix(CONTRIBUTING): fix broken links

- src/reference-guide/controller-api/v2.0.md
> ref(reference-guide): remove containers for pods

- CHANGELOG.md
- _scripts/generate-changelog.sh
also update changelog generation script
> doc(CHANGELOG.md): add changelog for beta2

- src/installing-workflow/configuring-object-storage.md
The title did not match with the document's name.
> ref(installing-workflow): fixup configuring object storage title

- src/contributing/releasing.md
> doc(releasing.md): add documentation on how to release a new Deis Workflow

- src/installing-workflow/installing-deis-workflow.md
> Update versions in install documentation

- src/installing-workflow/configuring-object-storage.md
Couple of things I wanted to accomplish here.
* Make the top of the doc goal oriented to actually walk folks through wiring this up.
* Remove as much repeated content as possible like the redundant helm charts sections.
* Expand on the paths and env vars used to help point folks in the right direction if debugging.
Pretty major rewrite, so I wanted to throw this up for feedback. Haven't given it a close read for spelling and grammar.
> doc(objectstorage): refactor configuring object storage documentation

- src/using-workflow/installing-the-client.md
The name has since changed to install-v2.sh
closes #126
> ref(using-workflow): update script name

- src/managing-workflow/configuring-dns.md
Fixes #146 
The original ticket was intended to provide instructions for configuring Cloud DNS for a GKE cluster. I think I was able to make them generic for any cluster that has a load balancer in front of the routers.
cc/ @jchauncey @slack
> doc(configuring-dns.md): adding instructions for configuring Google Cloud DNS for a Deis cluster

- src/contributing/releasing.md
Fixes https://github.com/deis/workflow/issues/185
Also removes errant tag & git SHA information from workflow-manager
> doc(releasing.md): add workflow-cli to the list of components

- src/contributing/releasing.md
after fixes are made
Fixes https://github.com/deis/workflow/issues/186
> doc(releasing.md): add note to update the git submodule SHAs

- src/reference-guide/controller-api/v2.0.md
> ref(reference-guide): bump DEIS_PLATFORM_VERSION to 2.0.0

- src/managing-workflow/operational-tasks.md
> feat(managing-workflow): add back operational tasks

- src/roadmap/release-checklist.md
> docs(release-checklist): set DEBUG=false in manifests

- src/index.md
- src/installing-workflow/installing-deis-workflow.md
- src/installing-workflow/quickstart.md
- src/installing-workflow/system-requirements.md
- src/understanding-workflow/concepts.md
Some corrections and improvements I thought we should make while reading through the current docs. More to come.
> docs(*): improve grammar and fix typos

- src/installing-workflow/configuring-object-storage.md
- src/installing-workflow/installing-deis-workflow.md
- src/managing-workflow/platform-logging.md
- src/managing-workflow/upgrading-workflow.md
- src/roadmap/release-checklist.md
> chore(src): bump documentation to reference v2.0.0-beta3

- CONTRIBUTING.md
- src/installing-workflow/configuring-object-storage.md
- src/installing-workflow/installing-deis-workflow.md
- src/managing-workflow/upgrading-workflow.md
- src/roadmap/release-checklist.md
- src/understanding-workflow/architecture.md
- src/understanding-workflow/concepts.md
> ref(helm): update the docs to refer helm classic instead of helm

- src/roadmap/release-checklist.md
Amending as we release beta4...
Closes https://github.com/deis/jenkins-jobs/issues/79
> docs(release-checklist.md): update with latest processes

- src/roadmap/release-checklist.md
Also, use new deisrel command for generating individual repository changelog.
Requires https://github.com/deis/deisrel/pull/53
Fixes https://github.com/deis/workflow/issues/231
Fixes https://github.com/deis/workflow/issues/230
> doc(release-checklist): use new deisrel command format

- src/roadmap/release-checklist.md
Ref https://github.com/deis/deisrel/pull/55
> docs(release_checklist.md): update with latest deisrel usage

- src/reference-guide/controller-api/v2.0.md
Required for https://github.com/deis/controller/pull/738
> ref(API): rc got renamed to exit_code in the API

- themes/deis/base.html
- themes/deis/nav.html
- themes/deis/static/js/adjustments.js
O_o - I felt really bad about this, but then I didn't. ¯\_(ツ)_/¯
> bug(quickstart/links): fix quick start links in toc

- src/installing-workflow/configuring-object-storage.md
> docs(installing-workflow): add docs on dockerbuilder config

- mkdocs.yml
- src/troubleshooting/index.md
- src/troubleshooting/kubectl.md
- src/troubleshooting/troubleshooting.md
> feat(troubleshooting): add troubleshooting docs

- src/quickstart/provider/aws/dns.md
closes #180 
(yes @mboersma this is in first person but just keeping the doc in the same tense as was written :stuck_out_tongue:)
> docs(quickstart): add DNS registrar and Route53 docs for AWS

- src/managing-workflow/production-deployments.md
... which is forthcoming in #253 
This was my bad as I merged a docs PR w/o noticing it depended on #253 first (which introduces the file linked to here)... 
cc @mboersma
> fix(production-deployments.md): comment link to non-existent doc

- src/installing-workflow/configuring-object-storage.md
- src/installing-workflow/index.md
- src/managing-workflow/component-configuration.md
- src/managing-workflow/upgrading-workflow.md
- src/quickstart/provider/aws/install-aws.md
- src/quickstart/provider/gke/install-gke.md
- src/quickstart/provider/vagrant/install-vagrant.md
- src/roadmap/release-checklist.md
- src/troubleshooting/kubectl.md
as per https://github.com/deis/workflow/blob/master/src/roadmap/release-checklist.md#step-3-update-documentation
Employed `git grep -l 'beta4' | xargs sed -i '' -e 's/beta4/rc1/g'` and just reset the unwanted change to `CHANGELOG.md`
> docs(various): update 'beta4' occurrences to 'rc1'

- src/managing-workflow/security-considerations.md
closes #247 
pinging @krancour for any input, as he knows the router best :)
> docs(managing-workflow): add Security Considerations

- src/roadmap/release-checklist.md
ref https://github.com/deis/workflow/issues/258 for proposal introducing most of these changes
also note some steps depend on https://github.com/sgoings/deis-workflow-group/pull/4
> docs(release-checklist.md): update from rc1 amended processes

- src/roadmap/release-checklist.md
To fix the markdown representation of this doc.
> docs(src/roadmap/release-checklist.md): adjust spacing

- src/applications/managing-app-configuration.md
See https://github.com/deis/controller/pull/779 for more information
> fix(health): remove documentation on unused HEALTHCHECK_PORT

- README.md
- _scripts/deploy.sh
- src/quickstart/install-cli-tools.md
Including updating relevant docs and altering
`VERSION` in _scripts/deploy.sh
Ref https://github.com/deis/workflow/issues/285
> chore(various): remove beta status

- src/roadmap/release-checklist.md
Requires https://github.com/deis/deisrel/pull/88
> doc(release-checklist.md): remove bintray references from the release checklist

- src/roadmap/release-checklist.md
As the release branch on deis/charts will now be created as part of
Step 1.1
Ref https://github.com/sgoings/deis-workflow-group/pull/6
> docs(src/roadmap/release-checklist.md): update Step 2.1

- src/contributing/submitting-a-pull-request.md
Much discussion around streamlining code review and approval led to consensus on this change.
ping @jchauncey
> docs(submitting-a-pr): add "hotfix revert" exception to LGTM rules

- mkdocs.yml
- themes/deis/base.html
Must be merged before https://github.com/engineyard/deis.com/pull/158
> chore(rtd): set canonical url for documentation to deis.com

- src/applications/managing-app-configuration.md
https://github.com/deis/controller/issues/774 has more insight
Closes https://github.com/deis/controller/issues/774
> chore(health): note that kubernetes does not support query params in the health check path

- src/roadmap/release-checklist.md
One of the outcomes from the last `v2.0.0` release (and subsequent retrospective) was
to return to the use of immutable tags in a release chart as opposed to the
mutable/'pretty' `$WORKFLOW_RELEASE` tags.
This change therefore represents the associated docs update.
> docs(release_checklist.md): return to using immutable tags

- themes/deis/sitemap.xml
> bug(sitemap): fix sitemap, drop ignored and invalid attributes

- src/contributing/submitting-a-pull-request.md
Ref https://github.com/deis/jenkins-jobs/issues/54
Ref https://github.com/deis/jenkins-jobs/pull/104
> docs(submitting-a-pull-request.md): add info on testing paired commits

- src/reference-guide/controller-api/v2.0.md
> fix(api): update out of date cert api docs

- src/managing-workflow/security-considerations.md
- src/quickstart/provider/vagrant/dns.md
https://github.com/deis/workflow/issues/346
> Fixes #346 - removes labels annotion in whitelist

- src/managing-workflow/component-configuration.md
Syncs up with the change in deis/controller#833.
> fix(component-config): clarify GUNICORN_WORKERS value

- src/applications/managing-app-configuration.md
> fix(applications): fixup exec probe output

- src/roadmap/release-checklist.md
Requires https://github.com/deis/deisrel/pull/89
> doc(release-checklist.md): modify docker tag/push instructions to use new deisrel command

- mkdocs.yml
- src/installing-workflow/configuring-postgres.md
Complements https://github.com/deis/charts/pull/286
cc @bacongobbler
> doc(database): Document off-cluster db configuration

- mkdocs.yml
- src/reference-guide/controller-api/v2.1.md
@helgi Did I overlook any API changes for this release (see the `What's New` section)
I just skimmed at the [commit diff between v2.0.0 and master](https://github.com/deis/controller/compare/v2.0.0...master?expand=1).
> feat(api): add v2.1 api documentation.

- src/quickstart/provider/aws/boot.md
> AWS kube-up looks for NODE_ROOT_DISK_SIZE

- src/roadmap/release-checklist.md
Ref https://github.com/deis/jenkins-jobs/pull/129
> docs(release_checklist.md): add brief description of <component>-release job

- src/roadmap/release-checklist.md
Ref https://github.com/deis/jenkins-jobs/pull/130
> docs(release_checklist.md): adjust step involving Jenkins job(s)

- src/roadmap/release-checklist.md
Depends on https://github.com/deis/deisrel/pull/112
> doc(src/roadmap/release-checklist.md): use deisrel for bulk-cutting release branches

- src/contributing/submitting-a-pull-request.md
to list PR number as opposed to commit sha value
Ref https://github.com/deis/jenkins-jobs/pull/132
> docs(submitting-a-pull-request.md): update instructions

- src/installing-workflow/configuring-object-storage.md
- src/managing-workflow/production-deployments.md
ref https://github.com/deis/workflow/issues/306
> feat(swift): Add swift as an object storage

- src/roadmap/release-checklist.md
> docs(release-checklist): bumping client/server versions

- src/roadmap/release-checklist.md
> docs(release-checklist): update release dance

- src/quickstart/provider/aws/boot.md
./clusters/kube-up.sh should be ./cluster/kube-up.sh
> docs(aws): typo in kube-up.sh path

- src/applications/deploying-apps.md
Fixes https://github.com/deis/workflow/issues/393
> doc(deploying-apps.md): fix broken link for k8s revisions

- _scripts/deploy.sh
- src/installing-workflow/configuring-object-storage.md
- src/installing-workflow/configuring-postgres.md
- src/installing-workflow/index.md
- src/managing-workflow/platform-logging.md
- src/managing-workflow/upgrading-workflow.md
- src/quickstart/provider/aws/install-aws.md
- src/quickstart/provider/gke/install-gke.md
- src/quickstart/provider/vagrant/install-vagrant.md
- src/roadmap/release-checklist.md
- src/troubleshooting/kubectl.md
Update docs to reflect v2.2.0 
@mboersma  Let me know if you want me to add NOTE for k8s bug and should try only for 1.2.5 . in this PR
> feat(update): update docs to reflect v2.2.0

- src/applications/deploying-apps.md
when deployments are turned on, the controller can crash on startup in
a very specific case
Ref https://github.com/deis/controller/issues/903
> doc(deploying-apps.md): add note about known issue in controller

- src/applications/using-docker-images.md
- src/applications/using-dockerfiles.md
closes https://github.com/deis/deis/issues/5064
> doc(dockerfiles): Add Bash to requirements list of Dockerfile/image

- src/applications/using-buildpacks.md
refs https://github.com/deis/slugbuilder/pull/86
> doc(applications): add pre-compile/post-compile hook docs

- src/applications/using-buildpacks.md
See https://github.com/deis/workflow/pull/405#discussion_r72348505
> docs(applications): fix up grammar under "Compile Hooks"

- src/installing-workflow/system-requirements.md
- src/quickstart/provider/aws/boot.md
- src/quickstart/provider/vagrant/boot.md
now that deis/charts#317 is merged
> docs(installing-workflow): remove insecure-registry documentation

- src/roadmap/releases.md
> docs(releases): add deisrel command to query released components

- src/installing-workflow/index.md
- src/installing-workflow/system-requirements.md
Thanks again to the Kubernetes team for pouncing on the secret mount bug and fixing it!
Closes #372.
> docs(installing): add k8s 1.3.4+ as supported

- src/installing-workflow/configuring-registry.md
This should be merged after corresponding code changes are merged.
> feat(registry): Add docs for configuring private registry

- src/roadmap/releases.md
Also removes a section that should have gone away with #425.
> docs(releases): tag workflow-* repositories

- src/managing-workflow/upgrading-workflow.md
I don't think we aid comprehension by parenthetically mentioning how to totally uninstall your cluster and prevent an upgrade in the flow of the "how to upgrade your cluster" document.
> chore(english language): upgrade != total uninstall

- src/applications/domains-and-routing.md
- src/reference-guide/terms.md
refs https://github.com/deis/controller/pull/934
> docs(applications): add deis routing docs

- src/roadmap/roadmap.md
Closes https://github.com/deis/workflow/issues/309
Linked to related issues from deis/deis for roadmap items where it makes sense. Many of these roadmap items still need Workflow/Kubernetes-focused proposals.
> chore(roadmap): update roadmap for 2.x

- src/applications/managing-app-configuration.md
Fixes https://github.com/deis/controller/issues/881
This should be merged after corresponding code changes are merged.
> feat(healthcheck): Add docs for applying healthchecks per proctype

- mkdocs.yml
- src/installing-workflow/index.md
- src/installing-workflow/system-requirements.md
> bug(docs): clarify object storage requirements

- src/applications/deploying-apps.md
Since https://github.com/deis/controller/issues/903 is fixed, this should not be an issue anymore, right?
> chore(docs): update docs to reflect fixed issue

- src/installing-workflow/configuring-object-storage.md
The bullet-ocolypse was getting a bit out of hand! Refactor into a table. Then
some small clean-ups for style, etc.
> doc(storage): cleanup storage docs

- src/managing-workflow/tuning-component-settings.md
closes https://github.com/deis/workflow/issues/449
> feat(docs): add documentation for limits

- src/users/cli.md
> feat(CLI): document new behavior of  variable

- mkdocs.yml
- src/troubleshooting/applications.md
- src/troubleshooting/index.md
> feat(troubleshooting): add troubleshooting applications

- src/applications/managing-app-lifecycle.md
Fixes https://github.com/deis/deis/issues/3722
This should be merged after corresponding code changes are merged.
> feat(maintenance): Add docs for maintenance mode support

- _scripts/deploy.sh
- src/installing-workflow/configuring-object-storage.md
- src/installing-workflow/configuring-postgres.md
- src/installing-workflow/configuring-registry.md
- src/installing-workflow/index.md
- src/managing-workflow/platform-logging.md
- src/managing-workflow/upgrading-workflow.md
- src/quickstart/provider/aws/install-aws.md
- src/quickstart/provider/gke/install-gke.md
- src/quickstart/provider/vagrant/install-vagrant.md
- src/roadmap/releases.md
Docs to reflect v2.4.0 changes
> feat(release): change docs to reflect v2.4.0 release

- _scripts/deploy.sh
- src/installing-workflow/configuring-object-storage.md
- src/installing-workflow/configuring-postgres.md
- src/installing-workflow/configuring-registry.md
- src/installing-workflow/index.md
- src/managing-workflow/platform-logging.md
- src/managing-workflow/upgrading-workflow.md
- src/quickstart/provider/aws/install-aws.md
- src/quickstart/provider/gke/install-gke.md
- src/quickstart/provider/vagrant/install-vagrant.md
- src/roadmap/releases.md
https://github.com/deis/charts/pull/342
> chore(release): Workflow 2.4.1

- src/quickstart/provider/aws/boot.md
- src/quickstart/provider/gke/boot.md
- src/quickstart/provider/vagrant/boot.md
also make changes to always reference the system requirements docs for
the latest compatible versions.
closes #466
> fix(quickstart): remove references to downgrade

- src/quickstart/deploy-an-app.md
> fix(quickstart): specify how to get hostname

- src/contributing/triaging-issues.md
> docs(triaging-issues): describe new priority labels

- src/contributing/overview.md
Adds in some content that was in our `CONTRIBUTING.md` file but not on this page.
cc @helgi
> feat(contributing): add more details to issue reporting

- _scripts/deploy.sh
- src/installing-workflow/configuring-object-storage.md
- src/installing-workflow/configuring-postgres.md
- src/installing-workflow/configuring-registry.md
- src/installing-workflow/index.md
- src/managing-workflow/platform-logging.md
- src/managing-workflow/upgrading-workflow.md
- src/quickstart/provider/aws/install-aws.md
- src/quickstart/provider/gke/install-gke.md
- src/quickstart/provider/vagrant/install-vagrant.md
- src/roadmap/releases.md
ref https://github.com/deis/charts/pull/344
> chore(release): Workflow 2.4.2

- src/reference-guide/controller-api/v2.3.md
See https://github.com/deis/controller/pull/1035
> chore(api-docs): add v2.3 API docs

- src/applications/managing-app-processes.md
> feat(autoscale): add documentation for the autoscale functionality

- src/roadmap/releases.md
Ref https://github.com/deis/jenkins-jobs/pull/230
Arbitrary choice in choosing Step 10... could be any after 5 really.
> docs(src/roadmap/releases.md): add step for releasing cli stable

- CONTRIBUTING.md
This updates it to be in line with the others.
> doc(CONTRIBUTING): update contributing documentation

- src/roadmap/roadmap.md
Refs https://github.com/deis/deis.com/pull/243
> chore(release): update roadmap for 2.5

- src/applications/deploying-apps.md
- src/managing-workflow/tuning-component-settings.md
Docs for https://github.com/deis/charts/pull/351
> feat(apps): add information about IMAGE_PULL_POLICY globally and per app

- src/installing-workflow/configuring-registry.md
Also fixes a missing hyperlink.
Closes #458.
> ref(configuring-registry): clarify ECR registry variables

- src/users/registration.md
> fix(docs): add documentation on resetting a password using the cli.

- src/installing-workflow/configuring-postgres.md
- src/managing-workflow/platform-monitoring.md
- src/managing-workflow/tuning-component-settings.md
- src/roadmap/releases.md
- src/understanding-workflow/concepts.md
> fix(docs): change the references from RC's to deploments

- src/managing-workflow/upgrading-workflow.md
closes https://github.com/deis/workflow/issues/510
Added nodes >=2 for upgrade to requirements section
> docs(src/managing-workflow/upgrading-workflow.md): document nodes >= 2 for upgrade

- src/roadmap/releases.md
Ref https://github.com/deis/workflow-manager-api-publish/pull/28
Ref https://github.com/deis/jenkins-jobs/pull/235
> docs(src/roadmap/releases.md): remove publish component release step

- src/roadmap/releases.md
Ref https://github.com/deis/jenkins-jobs/pull/238
> docs(src/roadmap/releases.md): link to pipeline flow diagrams

- _scripts/gutenbuild
refs one fix in #520. I tested this locally but failed to add -- into my commit. Sorry!
> fix(gutenbuild): prepend grep string with --

- _scripts/gutenbuild
This is the last fix. closes #351
> fix(gutenbuild): use dev_build_dest for second build

- src/managing-workflow/configuring-load-balancers.md
This adds a section on configuring PROXY protocol with a specific example targeting K8s on AWS using ELB.
Because of the fix in deis/router#263 this PR should likely be held back until Workflow v2.6.0 is released.
> docs(managing-workflow): Document PROXY protocol configuration

- src/roadmap/releases.md
> docs(releases): add missing details and reword CI flow reference

- _scripts/deploy.sh
- mkdocs.yml
- src/changelogs/v2.6.0.md
- src/installing-workflow/configuring-object-storage.md
- src/installing-workflow/configuring-postgres.md
- src/installing-workflow/configuring-registry.md
- src/installing-workflow/index.md
- src/managing-workflow/platform-logging.md
- src/managing-workflow/upgrading-workflow.md
- src/quickstart/install-cli-tools.md
- src/quickstart/provider/aws/install-aws.md
- src/quickstart/provider/gke/install-gke.md
- src/quickstart/provider/vagrant/install-vagrant.md
- src/roadmap/releases.md
> chore(changelogs): add v2.6.0 changelog

- src/roadmap/releases.md
A script in the charts repository removes much of the manual work here.
Requires deis/charts#363.
> docs(relases): simplify Workflow release step 4

- src/applications/managing-resource-limits.md
Fixes https://github.com/deis/workflow/issues/536
> fix(docs): correct docs for limits:set --cpu flag

- src/applications/using-docker-images.md
- src/applications/using-dockerfiles.md
I ran into an unclear (to me) issue that raised:
```
Error running git receive hook [publishing release (Unknown Error (400): {"detail":"PORT needs to be set in the config when using a private registry"})]
```
Thought I take my frustration and turn it into some improvements. Hope this is helpful. 😄 
- RE: deis/builder#433
- I tried to improve the error text as well here: deis/controller#1089
> Improve docs on PORT config when using a private registry

- src/installing-workflow/index.md
This is a good follow-up step after installing Workflow.
closes #532
> docs(installing-workflow): add followup link to register a user

- mkdocs.yml
- src/reference-guide/migration.md
> feat(reference-guide): add Deis v1 Migration Guide

- _scripts/deploy.sh
- mkdocs.yml
- src/changelogs/v2.7.0.md
- src/installing-workflow/configuring-object-storage.md
- src/installing-workflow/configuring-postgres.md
- src/installing-workflow/configuring-registry.md
- src/installing-workflow/index.md
- src/managing-workflow/platform-logging.md
- src/managing-workflow/upgrading-workflow.md
- src/quickstart/provider/aws/install-aws.md
- src/quickstart/provider/gke/install-gke.md
- src/quickstart/provider/vagrant/install-vagrant.md
- src/roadmap/releases.md
> Release v2.7.0

- src/managing-workflow/tuning-component-settings.md
https://github.com/deis/controller/pull/1099
Text feels a bit cramped in the table layout - Not going to change that in this PR but something to think about for settings with longer explanation
> feat(deploys): Add new configuration options to Controller introducedin controller/#1099

- charts/workflow/values.yaml
ref https://github.com/deis/jenkins-jobs/pull/276
> fix(charts): Add workflow manager production urls for the release charts

- src/understanding-workflow/components.md
> docs(components): adding workflow-manager to list of workflow components.

- mkdocs.yml
- src/managing-workflow/extending-workflow.md
What other projects should be listed here?
Closes #577. ping @olalonde
> docs(extending-workflow): add a list of community projects around workflow

- src/contributing/overview.md
- src/index.md
This adds a note to the homepage of the workflow documentation on how users can start contributing to the project.
> docs(index): add note on contributing

- src/roadmap/releases.md
Ref https://github.com/deis/deisrel/pull/146
> docs(src/roadmap/releases.md): update master changelog step

- src/applications/managing-resource-limits.md
Accept new cli format limits:set web=500m/2000m
Value is map to requests/limits parameter in Kubernetes resource management.
See https://github.com/deis/workflow/issues/562
> docs(limits-cmd): accept new limits:set value type

- src/applications/managing-app-configuration.md
- src/managing-workflow/security-considerations.md
> feat(docs): document `deis tags` under the "Applications" section

- src/managing-workflow/platform-logging.md
Unfortunately https doesn't work.
closes #614
> fix(managing-workflow): provide proper link to nsq.io

- src/applications/managing-resource-limits.md
fix display of `\<requests>`
after fix:
> fix(docs): fix resource limit display issue

- charts/workflow/values.yaml
ref https://github.com/deis/router/pull/288
> feat(charts): Add support to add annotations for router during install

- _scripts/deploy.sh
- mkdocs.yml
- src/changelogs/v2.9.0.md
- src/installing-workflow/chart-provenance.md
- src/installing-workflow/index.md
- src/managing-workflow/platform-logging.md
- src/roadmap/releases.md
> docs(*): update versions to v2.9.0 and add changelog

- src/quickstart/install-cli-tools.md
With current install steps, the version reported is 2.9.1
> update deis version number

- src/roadmap/releases.md
ref https://github.com/deis/deisrel/pull/152
> docs(src/roadmap/releases.md): update to use k/helm

- src/reference-guide/controller-api/v2.0.md
- src/reference-guide/controller-api/v2.1.md
- src/reference-guide/controller-api/v2.2.md
- src/reference-guide/controller-api/v2.3.md
Fixes https://github.com/deis/controller/issues/1165
> bug(docs): update docs to match real endpoint

- charts/workflow/values.yaml
THIS is the real fix.
closes deis/logger#127
> fix(values): redis params are in the redis chart

- charts/workflow/values.yaml
Description here is obviously minimal -- definitely open to further elaboration.  Main purpose was to get rid of existing description (copied over/mis-leading)
> chore(chart): update values file description

- charts/workflow/values.yaml
PR https://github.com/deis/fluentd/pull/72
> feat(charts): Add optional syslog endpoint setting to fluentd

- charts/workflow/templates/upgrade-job.yaml
> fix(upgrade): Use a random generated name for upgrade job so it be upgraded multiple times using helm

- src/managing-workflow/tuning-component-settings.md
Documentation for https://github.com/deis/controller/pull/1149
> docs(managing-workflow): Add docs about resource quota for application namespace

- _scripts/deploy.sh
- mkdocs.yml
- src/changelogs/v2.9.1.md
- src/installing-workflow/chart-provenance.md
- src/installing-workflow/index.md
- src/installing-workflow/system-requirements.md
- src/managing-workflow/platform-logging.md
- src/managing-workflow/upgrading-workflow.md
- src/quickstart/provider/aws/install-aws.md
- src/quickstart/provider/gke/install-gke.md
- src/quickstart/provider/vagrant/install-vagrant.md
- src/roadmap/releases.md
A couple of fixes were also applied to the release document to reflect some small nuances in the
release cycle.
> docs(*): update versions to v2.9.1 and add changelog

- src/managing-workflow/platform-logging.md
- src/managing-workflow/platform-monitoring.md
> fix(managing-workflow): update logging and monitoring docs to reflect helm v2

- mkdocs.yml
- src/managing-workflow/deploy-hooks.md
- src/managing-workflow/tuning-component-settings.md
Proposal for https://github.com/deis/controller/issues/1153.
> feat(managing-deis): add docs for deploy hooks

- src/roadmap/releases.md
Any other notes we should add inspired by the recent v2.9.1 release?
> docs(releases.md): add patch release notes

- src/installing-workflow/chart-provenance.md
- src/roadmap/releases.md
(`&& echo` no longer needed w/ helm v2.1.0)
> docs(*): remove need for echo after helm fetch verify; update sha256

- src/managing-workflow/tuning-component-settings.md
Documentation update for deis/controller#1156
> docs(managing-workflow): Add LDAP configuration

- README.md
Let users know that the Workflow team may be temporarily short-handed over the holidays. ☃️
> docs(README.md): add temporary holiday notice

- src/roadmap/releases.md
ref https://github.com/deis/jenkins-jobs/pull/303
> docs(releases.md): update to reference workflow-chart-stage job

- README.md
This reverts commit f16816ec9e4d55b9a0307ef549bc1ff596063b6c.
> Revert "docs(README.md): add temporary holiday notice"

- charts/workflow/values.yaml
ref https://github.com/deis/postgres/pull/178
> feat(charts): Add support to specify creds for in cluster db through values file

- charts/workflow/values.yaml
See https://github.com/deis/router/pull/296 for router chart changes
> feat(charts): Add router specific configurable variables

- charts/workflow/values.yaml
> fix(charts): enable hostports by default

- src/applications/using-buildpacks.md
- src/applications/using-dockerfiles.md
Links included the Markdown file extension.
> docs(applications) fix broken links for SSH keys

- src/managing-workflow/upgrading-workflow.md
Ref https://github.com/deis/registry-token-refresher/pull/7
Ref https://github.com/deis/workflow/pull/672
> docs(*): add upgrade note for gcs/gcr

- src/installing-workflow/configuring-object-storage.md
- src/managing-workflow/upgrading-workflow.md
there's actually a flag for this :)
> ref(upgrading-workflow): use -w 0 flag when base64 encoding

- src/quickstart/install-cli-tools.md
- src/quickstart/provider/azure-acs/boot.md
* Added Azure link to install cli tools
* Improved kubectl flow to get .kube config file from cluster
> docs streamline Azure quickstart

- src/quickstart/provider/vagrant/boot.md
> chore(vagrant): update kubernetes release tarball to v1.5.1

- src/applications/managing-app-configuration.md
> fix(applications): fixup --headers usage

- src/managing-workflow/production-deployments.md
refs deis/monitor#171
cc @sheerun
> docs(production-deployments): recommend disabling grafana signups

- src/understanding-workflow/components.md
> docs(components): document the monitoring stack

- mkdocs.yml
- src/reference-guide/controller-api/v2.3.md
> docs(api/v2.3): add TLS API examples and index v2.3 API

- src/quickstart/provider/aws/boot.md
Initial Commit (So this is probably a WIP)
But wanted to get eyes on the new docs in case anyone has feedback. I have a few questions/comments/concerns so I will mentioning them on the PR based on the line number.
Thanks!
> Using kops instead of kube-up.sh

- src/managing-workflow/platform-monitoring.md
(previous instructions seem to be from the helmc era)
> docs(platform-monitoring.md): update grafana un/pw set instructions

- src/managing-workflow/tuning-component-settings.md
> docs(tuning-component-settings): elaborate with practical examples

- charts/workflow/values.yaml
- src/managing-workflow/production-deployments.md
- src/managing-workflow/tuning-component-settings.md
- src/users/registration.md
> fix(charts): default registration mode to "admin_only"

- src/quickstart/provider/azure-acs/install-azure-acs.md
A couple of extra envvars are needed in the next step.
relates to #754's changes.
> fix(quickstart): prepend Azure envvars with AZURE_

- _scripts/deploy.sh
- mkdocs.yml
- src/changelogs/v2.12.0.md
- src/installing-workflow/chart-provenance.md
- src/installing-workflow/index.md
- src/quickstart/install-cli-tools.md
- src/roadmap/releases.md
> docs(*): updates/changelog for v2.12.0 release

- src/managing-workflow/tuning-component-settings.md
https://github.com/deis/controller/pull/1249
> feat(controller) default tags for all applications

- src/managing-workflow/tuning-component-settings.md
refs https://github.com/deis/builder/pull/492
Here's how it looks.
> docs(builder-nodeselector): add BUILDER_POD_NODE_SELECTOR document

- src/managing-workflow/tuning-component-settings.md
> fix(tuning-component-settings): convert toml to yaml

- src/applications/using-dockerfiles.md
related to work in https://github.com/deis/builder/pull/498.
> feat(using_dockerfiles): document build args feature flag

- _scripts/deploy.sh
- mkdocs.yml
- src/changelogs/v2.13.0.md
- src/installing-workflow/chart-provenance.md
- src/installing-workflow/index.md
- src/quickstart/install-cli-tools.md
- src/roadmap/releases.md
I also reversed the sorting on the changelogs index, since most-recent-first seems more user-friendly.
TODO:
> docs(*): updates/changelog for v2.13.0 release

- src/quickstart/deploy-an-app.md
This line is not needed in the docs, and will probably cause more problems than it solves.
Non breaking change, docs only
> fix(hostname): Fixing hostname line

- src/quickstart/provider/azure-acs/boot.md
This streamlines the docs to be easy to copy/paste the commands into a terminal.
> ref(azure/boot): export AZURE_DNS_PREFIX and use $HOME

- src/installing-workflow/experimental-native-ingress.md
- src/quickstart/provider/aws/dns.md
- src/troubleshooting/applications.md
- src/understanding-workflow/components.md
These DNS records will allow one to run `git push deis master` using experimental native ingress.
> feat(ingress): document deis-builder DNS records

- charts/workflow/values.yaml
- src/managing-workflow/production-deployments.md
PR to allow usage of https://github.com/deis/registry-proxy/pull/11
> Enable registry-proxy for CNI users

- mkdocs.yml
- src/changelogs/v2.14.0.md
- src/installing-workflow/chart-provenance.md
- src/installing-workflow/index.md
- src/quickstart/install-cli-tools.md
- src/roadmap/releases.md
> docs(*): updates/changelog for v2.14.0 release

- themes/deis/footer.html
- themes/deis/topbar.html
* update the navigation links for the Workflow Docs
* remove the Engine Yard message from the footer
> docs(chore): remove the services url navigation

- mkdocs.yml
- src/changelogs/v2.15.0.md
- src/installing-workflow/chart-provenance.md
- src/installing-workflow/index.md
- src/quickstart/install-cli-tools.md
- src/roadmap/releases.md
See also #822--some docs were commented out until we have a fix for chart verification.
> docs(*): updates/changelog for v2.15.0 release

- src/quickstart/provider/minikube/boot.md
Add instruction to set default minikube VM driver.
> docs(minikube/boot.md): Explain how to set default minikube VM driver.

- mkdocs.yml
- src/changelogs/v2.16.0.md
- src/installing-workflow/chart-provenance.md
- src/installing-workflow/index.md
- src/quickstart/install-cli-tools.md
- src/roadmap/releases.md
> docs(*): updates/changelog for v2.16.0 release

- src/changelogs/v2.16.0.md
Added builder to releases, and added the release docs commit while we're at it.
> docs(changelogs): add builder release and workflow commit

- src/quickstart/provider/minikube/dns.md
> Add instructions for DNSmasq

- src/quickstart/provider/minikube/dns.md
> fix(minikube/dns): Add precisions about dnsmasq

- README.md
If this wording is appropriate, I'll make a set of cookie-cutter PRs to include this in all the relevant repositories.
> docs(README.md): add notice of final release and maintenance mode

- src/_includes/install-workflow.md
Now RBAC is being more and more common, include how to use with deis in quickstart install docs.
> add note about RBAC to quickstart install 
