deis/workflow

- src/using-deis/using-buildpacks.md
The output from the builder needed to be updated to accurately reflect what the v2 builder outputs.  Since this needed to be updated anyway, I also switched the doc to using the example-go app instead of example-ruby-sinatra since the former seems to be the app we have tested with most often... and is also not prone to whatever bug seems to currently be affecting deployment of the latter.
> doc(deploying): Use example-go and update builder output

- src/using-deis/deploying-an-application.md
Fixes a broken link due, presumably, to re-organization of Docker's own doc tree.
> doc(deploying): Fix broken docker images link

- src/using-deis/deploying-an-application.md
Similar to #18...
This bundles three minor fixes. The first reference registration instructions-- we can't be telling unregistered users to login.
The second clarifies that the "Deis administrator" is the source of the controller URL.
The third removes the reference to use of the http://deis.local3.deisapp.com controller URL when using Vagrant. That is a vestige of v1. In DNS, deis.local3.deisapp.com round-robins through three specific private IPs where we used to run the VMs comprising a dev cluster. Now that we defer k8s provisioning on Vagrant to whatever scripts k8s includes for that purpose, we cannot make any guarantee that the VM(s) use any specific IPs.
> doc(deploying): Fix login instructions

- src/using-deis/registering-a-user.md
This bundles two minor fixes.  The first improves the clarity of the statement "you will be logged in automatically," which gave me just a minor head scratching moment when I read it.
The second removes the reference to use of the `http://deis.local3.deisapp.com` controller URL when using Vagrant.  That is a vestige of v1.  In DNS, `deis.local3.deisapp.com` round-robins through three specific private IPs where we used to run the VMs comprising a dev cluster.  Now that we defer k8s provisioning on Vagrant to whatever scripts k8s includes for that purpose, we cannot make any guarantee that the VM(s) use any specific IPs.
> doc(registering): Make minor fixes to registering doc

- src/using-deis/registering-a-user.md
Although it's still _probably_ a good idea to define a default domain on the router, that step is no longer strictly necessary, so the comment on this page about "The domain you use here should match the platform domain you selected when configuring the Router" is confusing and misleading.  Deleting it.
> doc(registering): Remove reference to platform domain

- CONTRIBUTING.md
Not a lot of point in continuing to link to a component we're not using.
> doc(contributing): Remove reference to deis/etcd

- src/installing-deis/system-requirements.md
This size requirement is no longer relevant.  Most of us routinely run locally on just a single node.  This removed text also speaks of etcd and ceph.  It needs to go.
> docs(sys-reqs): Remove cluster size requirement

- mkdocs.yml
- src/contributing/development-environment.md
- src/contributing/overview.md
- src/installing-deis/bare-metal.md
- src/installing-deis/digitalocean.md
- src/installing-deis/quickstart.md
Completely inconsistent with how we called out our preferred zero-to-k8s options, we still had individual pages (albeit placeholders) for bare metal and DigitalOcean.  This PR removes those pages and amends our list of preferred zero-to-k8s options with a link to the k8s doc's own (non-exhaustive) table of project-supported and community-supported options.
At the same time, I also removed references to DigitalOcean as our prefered development environment because there is no officially supported k8s on DigitalOcean-- only a community-supported option-- _and_ we have not really tested v2 on that platform ourselves yet either.
> doc(install/contrib): Remove DO and bare metal instructions

- src/installing-deis/installing-deis-workflow.md
Update install instructions to include `helm generate` step.
Fixes #15
> doc(install): fixup helm invocations

- src/managing-deis/platform-ssl.md
The `mkdocs` build is currently broken due to an incorrect internal link:
```console
$ make build
...
DEBUG   -  Building page managing-deis/platform-ssl.md 
ERROR   -  Error building page managing-deis/platform-ssl.md 
Error: The page "managing-deis/platform-ssl.md" contained a hyperlink to "reference-guide/creating_self_signed_ssl.md" which is not listed in the "pages" configuration.
make: *** [build] Error 1
```
> fix(platform-ssl.md): update link to self-signed SSL doc

- src/installing-deis/installing-deis-workflow.md
This improves the clarity of the installation instructions a little bit by moving the instructions re: the `helm fetch` command from the section that documents adding the deis/charts repo to the section that documents the other install-related helm commands.
I also removed the `helm update` command which seems like an irrelevant operation wrt to installing a package from a chart repo we've _just_ added.
> doc(installing): Minor refactor of install docs

- mkdocs.yml
Page was missing from `mkdocs.yml`.
> doc(pages): fix the build, reference object storage

- src/understanding-deis/components.md
Because of recent rewording of headings in the components doc, links from the architecture doc to specific sub-sections of the components doc were semi-broken.  They'd get you to the right page, but wouldn't take you to the desired section.  This PR corrects that.
> doc(understanding): Fix semi-broken links

- src/index.md
The existing welcome page stutters by telling us twice in the first two sentences that Deis is a PaaS.  This PR corrects that by collapsing these two sentences and re-organizing those that immediately follow.
> doc(welcome): Fix repetition of 'Workflow is a PaaS'

- src/understanding-deis/architecture.md
I may need to beg forgiveness for picking this nit.
There is nothing technically wrong with this sentence, but as soon as you've read "Every platform component and applications," it sounds very strange because the adjective "every" doesn't seem to agree with the plural "applications."  If you read on, the sentence eventually makes sense, but it was confusing enough to me that I had to read it twice.
Also, "every platform" doesn't sound like it agrees with the verb "expect."  Again, after a couple readings, the meaning becomes clear because it's the _collective_ of "every platform component and applications..." that are the subjects of the verb "expect."  But it's better when sentences don't require multiple readings to parse.
This simple fix makes it flow a bit better.
> doc(architecture): Improve sentence flow

- mkdocs.yml
- src/index.md
- src/installing-deis/quickstart.md
- src/understanding-deis/components.md
- src/understanding-deis/concepts.md
- src/using-deis/deploying-an-application.md
Few changes here:
* drop "See Also" breadcrumbs at the bottom of the concepts page, help folks find the next thing to read
* break up components sections by adding some visual difference
* deploying application sent folks off to external sites that weren't helpful for the current activity
* add a final step to quickstart, which is deploying an application
* surface quickstart so it shows up in the table of contents
* concepts before architecture
> Tweak structure to accommodate reader flow

- src/installing-deis/configuring-object-storage.md
I double-checked this with @helgi and it's not quite accurate that the workflow component (what will be called controller, I guess, going forward) is dependent upon object storage.  As such, this PR strikes it from the list of components that depend on object storage.
> doc(obj-storage): Remove workflow/controller from list

- src/installing-deis/installing-deis-workflow.md
Another nit...
Reading through the docs, I felt assaulted by the continuous use of `monospacing` in reference to Helm.  It looks awkward in places where it's referring to the _product_ and not referring explicitly to either a _command_ that someone is meant to or to output _from_ some command.
By fixing this and also upcasing it to "Helm," Helm gets a little more respect as a product-- which it deserves.
I also changed the link that read "installing helm" to "Helm's own documentation," because I felt that was more appropriate, given that we're not linking to another section of the Workflow documentation, but rather to something external.
> doc(installing): Don't always monospace helm

- src/using-deis/deploying-an-application.md
Another nit.  This make the reference to "Twelve-Factor App" methodology match how it already appears on the concepts page of this same documentation and on 12factor.net's own site.
> doc(deploying): Make references to 12factor consistent

- src/managing-deis/configuring-dns.md
Sometimes the little things (like a trailing slash) take longer to figure out than you want to admit. Hopefully this saves somebody else some troubles :)
> doc(configuring-dns): Tip about not forgetting trailing slash

- src/using-deis/using-docker-images.md
- src/using-deis/using-dockerfiles.md
Nits... This PR monospaces Dockerfile directives, which seems more proper, and just generally improves the precision of language with respect to these requirements.
> doc(using dockerfiles): Apply minor cleanup

- src/using-deis/process-types-and-the-procfile.md
There was a lot of repetition of information in the process type docs.  I think it told me _three_ times that the `Procfile` goes in the root of my application's source tree.  I've edited this page to be a bit more concise.
> doc(process types): Eliminate repition and generally polish

- themes/deis/base.html
- themes/deis/static/css/main.css
Build a callout so folks aren't confused between the different versions of
documentation.
> core(docs): callout doc version explicitly

- src/installing-deis/configuring-object-storage.md
also adds the database component to the list of things that needs S3
Fixes deis/builder#197
cc/ @smothiki
> doc(configuring-object-storage.md): add section on storing credentials & GCS

- src/managing-workflow/configuring-dns.md
- src/managing-workflow/configuring-load-balancers.md
This is a reorganization of existing information for better flow, with minor edits for accuracy and brevity.
I also include a link to the router's own docs from the load balancer page, since _this_ page references the load balancer page.  I simply wanted readers to have further opportunities to go deeper and deeper into the details if they so choose.
> doc(configuring-dns): Rewrite DNS docs for brevity and correctness

- mkdocs.yml
This PR just moves the page on configuring load balancers ahead of the page on configuring DNS in the doc tree.  I feel this is a more logical order in which to present these topics to someone who is new to managing Workflow.
Note the load balancer page needs some rework still, but I'll open a separate issue and PR for that.
> doc(mkdocs): Put LB docs before DNS in tree

- src/contributing/maintainers.md
The removed list of core maintainer is replaced with a link to https://github.com/orgs/deis/teams/core-maintainers
> doc(maintainers): Fix broken bulleted list and remove list of maintainers

- mkdocs.yml
- src/managing-workflow/managing-disk-usage.md
afaik (and someone correct me, _please_, if I have this wrong), the kubelet handles "garbage collection" for dead containers and stale/unused images.  In contrast to Deis v1.x, I don't think there's anything to really say on the topic of managing disk usage.
> doc(managing): Remove managing disk usage page

- src/installing-workflow/configuring-object-storage.md
We have plans in https://github.com/deis/builder/issues/266 to enable other regions
> doc(object-storage): note that S3 and GCS store in the respective default regions

- mkdocs.yml
- src/understanding-workflow/components.md
This extension creates internal links for all headers.
See https://pythonhosted.org/Markdown/extensions/toc.html
fixes #122
> feat(mkdocs): enable toc extension

- themes/deis/base.html
optimally we should replace this with a slack icon, but our social menu palette doesn't have a slack icon.
closes #121
> ref(themes/deis): remove IRC from social menu

- README.md
Until we have a more sophisticated "try/get-started" page on deis.com we are sending folks to `deis/workflow`. Updated the copy to direct folks to the next logical step in the setup process.
Fixes engineyard/deis.com#102
> doc(readme): help readme function as a landing page

- src/installing-workflow/installing-deis-workflow.md
Many users have missed this step, causing errors to pop up when
pushing to their cluster. This makes it so it is more apparent
that this is an important step in the setup process.
closes #149 
closes #150
> feat(installing-workflow): add ELB install notes

- themes/deis/base.html
The version list is not being shown on readthedocs.org because it's
not in the navigation list.
addresses #1 but will keep open as I cannot verify until it's pushed and deployed to readthedocs. No breaking changes occurred locally, however.
> fix(themes): fix up navigation on readthedocs

- mkdocs.yml
- src/managing-workflow/using-a-proxy-server.md
We have no documentation on this, nor does kubernetes. Removing for
the time being until we add this back.
> ref(docs): remove "using a proxy server"

- src/installing-workflow/system-requirements.md
workflow-beta2 and workflow-dev do not work on kubernetes 1.1 clusters.
> fix(installing-workflow): bump requirement to kubernetes 1.2

- src/contributing/releasing.md
The changes in this patch ensure that Makefile targets that require environment variables are run with those environment variables present.
> doc(releasing.md): merge makefile targets that require env vars

- src/contributing/releasing.md
It's easier to update and patch the charts repo with the entire new helm chart, including `README.md` and `Chart.yaml` updates, at once
> doc(releasing.md): merge helm documentation update step into the helm chart update step

- src/installing-workflow/installing-deis-workflow.md
I got bitten by this - secretkeyref is used by the workflow chart and breaks on earlier versions of k8s.
> Mention k8s 1.2 or higher is required

- src/installing-workflow/quickstart.md
the kubernetes documentation has broken these links. It's probably better to reference the
top-level "Getting Started Guide" to prevent this from happening again.
fixes #204
> fix(installing-workflow): fix getting started guide links

- README.md
[skip ci]
Adds a status badge that shows current participants in the https://slack.deis.io/ Slack channels and links to its signup page. Click on "View" here to see.
I'm not sure that's the best location for such a badge, but I thought this was nifty free functionality that could encourage community participation. Let me know if it should be relocated, and whether this is worthwhile.
> docs(README.md): add slack signup & status badge

- src/roadmap/release-checklist.md
CI-generated workflow charts for dev and testing currently instruct `workflow-manager` to source versions data from `https://versions-staging.deis.com`. This is a reminder to point to `https://versions.deis.com` as a part of the release process.
> doc(release): add an extra step to point to versions.deis.com

- src/roadmap/release-checklist.md
This process is completely automated now, so there should be a reduced amount of human error when
closing milestones.
> ref(release-checklist): update "close github milestones"

- mkdocs.yml
- src/customizing-workflow/tuning-component-settings.md
In v1 we had a section dedicated to customizations that users could
add to each component. This brings back that documentation back,
adding only controller and database-specific customizations to the
mix with others to be added as necessary.
addresses #75
> feat(customizing-workflow): add component tuning

- src/using-workflow/using-docker-images.md
some users were getting confused what exactly should be in the username/password fields. Clarifying
that these are identical to what's used in `docker login` should help clear up the air.
> docs(using-workflow): clarify what username and password reflect

- src/managing-workflow/platform-logging.md
- src/managing-workflow/upgrading-workflow.md
- src/roadmap/release-checklist.md
missed this undocumented step when cutting the release. All the documentation still references workflow-beta3. I've added a new step in the release checklist to ensure we don't miss this again. :)
> chore(src): bump docs to workflow-beta4

- src/managing-workflow/platform-logging.md
Daemon sets are standard with kubernetes v1.2 and is pointed out in the system requirements.
> docs(managing-workflow): remove daemon set warning

- src/index.md
- themes/deis/base.html
We don't require the warning on every page, and it's not something that needs to stick out on the landing page.
closes #83
> docs(index): move version header to index

- src/managing-workflow/upgrading-workflow.md
Upgrade still works with Minio of course, but loses all data, giving the user a "clean" platform. That's a dev workflow that didn't seem worth documenting here.
> docs(upgrading-workflow): require off-cluster storage for upgrade

- src/managing-workflow/upgrading-workflow.md
If this step is missed during upgrade, the controller and database won't be able to communicate.
I also removed the `helmc update` line since `helmc fetch` will do that for you if it doesn't find the chart referenced.
> docs(upgrading-workflow): copy DB creds into new chart

- src/reference-guide/controller-api/v2.0.md
The API is now v2, but docs still reference v1.
example:
```
$ curl -H "Content-Type: application/json" -X POST \
-d '{"username": "admin","password": "admin","email": "admin@example.com"}' http://deis.10.233.62.119.nip.io/v2/auth/register/
```
> fix(reference-guide/controller-api): v1->v2

- src/managing-workflow/upgrading-workflow.md
Since this operation _can_ be very destructive, rework the documentation to add
more safety nets.
* show requirements first
* pull database and builder secrets from the active cluster
* show how to check for `helm-keep: true`
* do all the template manipulation _before_ uninstalling workflow
> doc(upgrades): expand upgrade documentation

- src/quickstart/install-cli-tools.md
The version of hemlc currently installed via the links in this guide do not support `hemlc version`, but do support `hemlc --version`. Perhaps the syntax was changed recently.
> helmc version command

- src/quickstart/provider/vagrant/dns.md
I think ```route add <host> <gw>``` probably works on mac, but for sure doesn't work on linux.
> docs(src/quickstart/provider/vagrant/dns.md): fix route command for linux

- src/managing-workflow/platform-ssl.md
Hi, the example manifest in the docs regarding Platform SSL setup needs to be corrected. The relevant  keys to specify the certificate and the key are `tls.crt` and `tls.key` (instead of `cert` and `key`).
See:
https://github.com/deis/router/blob/eb6b05c55873805c87cf69297c8ae32bf3f532cd/README.md#platform-certificate-example
> docs(platform-ssl.md): correct example manifest

- src/roadmap/release-checklist.md
This adds documentation pertaining to exporting and usage of the `WORKFLOW_PREV_RELEASE ` environment variable (previously `WORKFLOW_OLD_RELEASE `).
> doc(release-checklist): Improve instructions pertaining to previous release

- src/applications/managing-app-configuration.md
- src/reference-guide/controller-api/v2.0.md
This is a summarized write-up of the proposal made in deis/controller#603. Note that I'm still a bit iffy on how the client should handle the [HTTP header section](http://kubernetes.io/docs/user-guide/liveness/) in the user guide, but it's up for pondering!
> docs(applications): add documentation for healthchecks

- src/applications/deploying-apps.md
- src/managing-workflow/tuning-component-settings.md
- src/understanding-workflow/concepts.md
> feat(deployments): add Deployments documentation

- src/roadmap/release-schedule.md
This document explained what in Deis v1 was considered a breaking change, what occurred during a release, what a patch/minor/major release entails, and our release cadence. This PR brings it up to date with what we now call "Workflow" with its new release cadence as well as what we consider to be breaking API changes.
This is by no means final, but this PR does reflect what we discussed earlier today in the release process meeting.
> docs(roadmap): update release schedule terms for Workflow

- themes/deis/base.html
I think the distracting big red banner about "You're viewing the latest release...for 1.0 click here" can be scrapped now that 1.0 has been in maintenance mode for a while. But maybe I'm jumping the gun? ping @slack.
> docs(base.html): remove link to Deis 1.0 docs

- src/installing-workflow/index.md
- src/installing-workflow/system-requirements.md
Until https://github.com/kubernetes/kubernetes/issues/28616 and https://github.com/kubernetes/kubernetes/issues/28750 are fixed, Deis Workflow cannot start successfully on Kubernetes 1.3.x.
> docs(install-workflow): note that k8s 1.2.x is required

- src/managing-workflow/upgrading-workflow.md
This PR looks forward to the workflow-v2.2.0 release. I also updated a reference to the `workflow-rc1` chart because while it's technically correct, we don't want to encourage anyone to use the old release candidate builds.
Fixes #391.
> docs(upgrading-workflow): update chart versions

- src/roadmap/releases.md
@vdice suggested that the CHANGELOG content for a release should also be added as an annotation on the `git` tag itself.
> docs(releases): paste CHANGELOG into tag annotation

- mkdocs.yml
Although documentation was recently added that details how to configure Workflow to use an external registry, that documentation was never included in the doc tree. This PR corrects that.
> fix(installing): Add configuring registry docs to doc tree

- src/managing-workflow/security-considerations.md
Fixes https://github.com/deis/controller/issues/240
This should be merged after corresponding code changes are merged.
> feat(whitelist): Add docs for specifying application whitelist using deis client

- src/understanding-workflow/components.md
Think this was just a simple copy and paste error from the concepts page.
> fix(components): link to architecture, not itself

- src/managing-workflow/tuning-component-settings.md
"redis" is the default in current Workflow charts.
> docs(tuning): update storage default for logger

- src/applications/deploying-apps.md
- src/applications/managing-app-configuration.md
- src/installing-workflow/configuring-object-storage.md
This PR adds the documentation for the slugbuilder cache implemented in deis/builder#421, deis/builder#419, deis/builder#412 and deis/slugbuilder#99.
> docs(slugbuilder-cache): add docs for the slugbuilder cache

- _scripts/gutenbuild
Since gutenberg uses rsync to pull in the projects for building the docs, the tags *should* be available for building.
ping @slack; Would this be the right way to do it?
closes #351
> feat(_scripts): build every tagged version of workflow docs

- _scripts/gutenbuild
The pre-release tags do not have the `make deps` or `make build` targets. This PR removes them from the build process.
> fix(gutenbuild): do not build any pre-release tags

- src/managing-workflow/upgrading-workflow.md
Added upgrade instructions to preserve existing the platform SSL certificate and private key. Installations that enforce SSL for all HTTP requests via `router.deis.io/nginx.ssl.enforce` *must* do this or operators may find themselves in quite the [head-scratching moment as applications continue to function yet the CLI, grafana, and other components requiring SSL fail](https://deis.slack.com/archives/community/p1476740206006301).
> (docs)Add instructions to preserve platform SSL credentials

- src/roadmap/releases.md
Manual tasks are now mostly gone in favor of running the `deisrel release` command.
See also deis/deisrel#140.
> docs(releases): update component release steps

- src/roadmap/releases.md
Workflow has grown into a mature and stable product, and the team at Deis thinks doing a minor release every two weeks may not be productive. This proposes to change the Deis Workflow release policy to "first Thursday of each month," but the actual change is dependent on your feedback. So please comment here as to whether or not that's a useful release policy for you!
See also deis/seed-repo#48.
> docs(releases): workflow releases happen monthly

- src/applications/managing-app-processes.md
Provides an example of how to read a `Procfile` located in another directory.
> doc(processes): add example of reading Procfile in different directory

- mkdocs.yml
- src/contributing/overview.md
- src/installing-workflow/chart-provenance.md
- src/installing-workflow/configuring-object-storage.md
- src/installing-workflow/configuring-postgres.md
- src/installing-workflow/configuring-registry.md
- src/installing-workflow/index.md
- src/managing-workflow/tuning-component-settings.md
- src/managing-workflow/upgrading-workflow.md
- src/quickstart/index.md
- src/quickstart/install-cli-tools.md
- src/quickstart/provider/aws/install-aws.md
- src/quickstart/provider/gke/install-gke.md
- src/quickstart/provider/vagrant/install-vagrant.md
- src/reference-guide/migration.md
- src/troubleshooting/kubectl.md
- src/understanding-workflow/architecture.md
- src/understanding-workflow/concepts.md
This changes all documentation to use Helm as the default tool for installing Deis
Workflow. Users of Helm Classic are urged to use https://github.com/deis/workflow-migration
to migrate from Helm Classic to Helm.
Note that I kept roadmap/releases.md intentionally left unchanged for now as we are still pumping out Helm Classic charts for v2.9.0 as far as I'm aware.
> docs(*): migrate from Helm Classic to Helm

- src/contributing/development-environment.md
`deis-docker` is transposed as `docker-deis` in a couple places. The original docker-machine machine is created as `deis-docker` so I figure that's the correct one.
> Quick update to contributer docs for consistency

- src/quickstart/provider/gke/boot.md
Note that I'm a total newcomer to Deis. I also haven't verified this problem/fix from a technical point of view. It's worth sharing the fix here, though, in case it **is** verified and we want to fix it.
When I ran `$ kubectl cluster-info`, I got this error:
`error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.`
Looks like the auth mechanism was updated a few months ago: https://github.com/kubernetes/kubernetes/issues/30617
> Previously, gcloud would have configured kubectl to use the cluster's static client certificate to authenticate. Now, gcloud is configuring kubectl to use the service account's credentials.
> 
> Kubectl is just using the Application Default Credentials library, and it …
> Update command used to auth to kubernetes host

- src/installing-workflow/system-requirements.md
Workflow is incompatible with Kubernetes v1.5.0 at this time. Putting up a warning for now to steer others from installing Kubernetes v1.5.0 with Workflow.
> docs(system-requirements): add warning for k8s 1.5

- src/installing-workflow/index.md
- src/installing-workflow/system-requirements.md
- src/quickstart/provider/aws/boot.md
We have not tested nor seen anyone use k8s v1.2 so I think it's fair to start dropping "official"
support for that minor release and just test against v1.3.4+ clusters.
> docs(installing-workflow): deprecate support for v1.2 clusters

- .dockerignore
- Dockerfile
Now anyone that builds the documentation can run:
```
docker build -t deisdocs:canary .
docker run -dp 8000:8000 deisdocs:canary
```
And open 127.0.0.1:8000 in their browser to view the docs.
> feat(Dockerfile): make the Dockerfile more functional

- src/roadmap/releases.md
We are no longer releasing helm-classic charts, so this link will 404.
> fix(releases): remove reference to deis/charts in release notes

- charts/workflow/templates/objectstorage-secret.yaml
- charts/workflow/values.yaml
- src/installing-workflow/configuring-object-storage.md
To support passing json data via `--set` at `helm install` time.
Previously, the json data was expected to be un-encoded in the `values.yaml`, which worked fine at install time if `-f values.yaml` was used.  However, there is seemingly no easy way to pass json data via `helm install --set`...
TODO:
> ref(*): require key_json chart value to be base64-encoded

- src/managing-workflow/upgrading-workflow.md
Helm doesn't like it when the base64-encoded string is wrapped in double quotes. Perhaps this is an
intentional thing due to the yaml parser, but it is good to call it out here.
> docs(upgrading-workflow): add note about using single quotes around base64 encoded string

- _scripts/deploy.sh
- mkdocs.yml
- src/changelogs/v2.10.0.md
- src/installing-workflow/chart-provenance.md
- src/installing-workflow/index.md
- src/quickstart/install-cli-tools.md
- src/roadmap/releases.md
> docs(*): update versions to v2.10.0 and add changelog

- src/roadmap/releases.md
This is how ~~(I think)~~ we've been doing releases of the `workflow` repo anyway, and it seems more logical to ensure that the v2.10.0 changelog is actually included in the v2.10.0 tag.
Also makes clear that we release workflow and workflow-cli in lockstep with the overall Workflow platform release, which we do.
> docs(releases): move workflow docs release after changelog PR

- src/quickstart/provider/azure-acs/install-azure-acs.md
premium storage does not support block blobs, whereas regular storage does.
Error coming from wal-e, which makes workflow completely unusable with this setup:
```
azure.storage._http.HTTPError: Block blobs are not supported.
```
cc @dtzar @slack.
closes #693.
> fix(azure): use regular storage instead of premium

- src/managing-workflow/tuning-component-settings.md
This was accidentally misplaced under workflow-manager settings, which confused a user in the Helm channel.
> fix(tuning-component-settings): move LDAP settings under Controller

- src/roadmap/roadmap.md
Some things have been completed (such as deploy hooks) since the last roadmap update.
This commit also removes a few bullet points from the roadmap that have been dangling since v2.0
or have not been followed up with tickets/design docs (such as the controller emitting metrics).
cc'ing @sgoings @slack on whether we still want to create tickets for these enhancements.
> chore(roadmap): update product roadmap

- src/installing-workflow/configuring-object-storage.md
Modify configuring-object-storage.md to warn users not to use periods in S3 bucket names.
Related to https://github.com/deis/workflow/issues/700
> doc(installing-workflow): no periods in S3 bucket names

- src/quickstart/provider/azure-acs/boot.md
- src/quickstart/provider/azure-acs/install-azure-acs.md
- The az command to create a service principal changed once again, so the steps were broken. 
- Provisioning an ACS/Kubernetes cluster now will automatically create a new service principal, so wanted to remove these steps and punt the service principal creation still required for the UI creation to the maintained document on docs.microsoft.com.
- Fixed a problem with the AZ command to properly capture storage account  key.
- Removed switch to disable TLS verification for controller with helm install
> docs(Azure): enhancement and fixes

- src/quickstart/provider/aws/boot.md
Some things have changed about `kube-up.sh`; this keeps the quick start for AWS current.
> docs(aws): update for latest k8s version available

- src/roadmap/releases.md
Ref/requires https://github.com/deis/deisrel/pull/157
> docs(src/roadmap/releases.md): simplify docs in global changelog step

- src/managing-workflow/configuring-load-balancers.md
This updates the docs to describe how to persist the AWS ELB idle timeout by using the proper k8s service annotation instead of following the manual instructions, which get reset if k8s re-configures the ELB.
The annotation was added in kubernetes/kubernetes#30695 and merged targeting k8s v1.4 in August 2016. I have verified that it works as expected on k8s v1.4.6.
> docs(managing-workflow) Document k8s annotation for AWS ELB idle timeout

- charts/workflow/requirements.yaml
- charts/workflow/values.yaml
I didn't see a requirements.lock so I assume that's handled by CI.
closes #644
> feat(charts): introduce kube-registry-proxy

- src/quickstart/provider/azure-acs/boot.md
A couple of fixes in this commit:
- prefix all environment variables with `AZURE_` for convenience
- change --agent-count=1 for trial accounts
- reference /home/myuser for the SSH key
> fix(quickstart): update azure quickstart docs

- src/installing-workflow/index.md
- src/quickstart/provider/azure-acs/install-azure-acs.md
The docs weren't consistent everywhere about requiring helm v2.1.3 or later.
> docs(installing): specify helm v2.1.3 as minimum everywhere

- charts/workflow/requirements.yaml
- charts/workflow/values.yaml
Reverts deis/workflow#734
We've seen issues where the `kube-registry-proxy` pod is not created after an upgrade to v2.12.0
> Revert "feat(charts): introduce kube-registry-proxy"

- src/applications/managing-app-processes.md
Ref https://github.com/deis/controller/pull/1261
> docs(managing-app-processes.md): update proc type naming guidelines

- src/applications/managing-app-configuration.md
The previous link, https://kubernetes.io/docs/user-guide/pod-states/#container-probes, displays a message about Kubernetes docs being moved, and includes a link to the new location for the particular topic. (And no longer includes the content/documentation). 
I've updated the link to the new location, and proper heading anchor, in the Kubernetes Pod Lifecycle documentation: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
> docs(managing-app-configuration): update "kubernetes-probes" link

- src/managing-workflow/configuring-load-balancers.md
Ref https://github.com/deis/router/pull/327
> docs(configuring-load-balancers.md): mention forthcoming default

- mkdocs.yml
- src/applications/inter-app-communication.md
Here's a first draft at documenting communication between Deis apps, which would fix https://github.com/deis/workflow/issues/
I spent a lot of time trying to come up with a simple example of an http-client app which resolves an app's URL to its internal IP address. I couldn't find an existing docker image which runs properly on Deis, as I don't have a great understanding of what kind of docker image a Deis app can simply run. I found a "ping" image which successfully demonstrates DNS resolution, but the pings fail when run in Deis.
LMK of any other info which should be contained here. I'll probably take a second review later.
> docs(src/applications/inter-app-communication.md) Add first draft

- charts/workflow/requirements.yaml
- charts/workflow/values.yaml
- mkdocs.yml
- src/installing-workflow/experimental-native-ingress.md
- src/installing-workflow/index.md
- src/quickstart/deploy-an-app.md
This is just a rebase of #732 to see if we can avoid the CI issues it was running into. All credit goes to @kris-nova of course.
Work for experimental native ingress. Run the documentation to see how to use the new feature.
Requires deis/controller#1243
Requires deis/builder#495
Requires deis/router#316
> feat(ingress): experimental native ingress

- src/quickstart/provider/gke/boot.md
When installing gcloud and kubectl using apt-get the user needs to
download the credentials. (At least that was the case for me).
> docs(gke/boot): Add info on obtaining credentials

- Makefile
- src/managing-workflow/platform-monitoring.md
- src/managing-workflow/tuning-component-settings.md
This updates several parts of the documentation related to monitoring it also adds a new make target called `run` which basically builds the docker image and calls `docker-serve`.
addresses part of https://github.com/deis/monitor/issues/171
Testing Steps:
* Clone PR
* `make run`
*  `Tuning Component Settings` page now has an updated Monitoring section
*  `Platform Monitoring`
* Removed the section on creating the `Storage Class`
* Added section on customizing (which takes you to the `Tuning Component Settings` page
* Added a section on the 2.9.0 release of Monitoring and the changes to the InfluxDB chart
> docs(monitoring): Update docs to reflect monitor chart changes

- charts/workflow/values.yaml
- src/installing-workflow/index.md
- src/managing-workflow/production-deployments.md
One commit to rule them all:
- https://github.com/deis/builder/pull/513
- https://github.com/deis/controller/pull/1292
- https://github.com/deis/fluentd/pull/96
- https://github.com/deis/monitor/pull/195
- https://github.com/deis/router/pull/344
> RBAC support

- src/installing-workflow/index.md
The former command would log a warning "Warning: Tiller is already installed in the cluster" and restart with the old configuration rather than using RBAC configuration. After replacing with helm reset the issue was resolved and new tiller was successfully installed.
> docs(installing-workflow) to remove helm using the reset command

- src/quickstart/deploy-an-app.md
I got error when I read and type command from quick start document
https://deis.com/docs/workflow/quickstart/deploy-an-app/
Document says that "`$hostname` will be `1.1.1.1.nip.io`" but it's not working.
It should be `deis.1.1.1.1.nip.io`, right?
Followings are error that I got.
```console
$ deis register http://1.1.1.1.nip.io
Error: http://1.1.1.1.nip.io does not appear to be a valid Deis controller.
Make sure that the Controller URI is correct, the server is running and
your deis version is correct.
```
> Add `deis.` prefix for $hostname

- src/_includes/install-workflow.md
- src/installing-workflow/index.md
- src/quickstart/provider/azure-acs/install-azure-acs.md
- src/quickstart/provider/minikube/install-minikube.md
We don't test with old versions of Helm, so this simplifies the story for supporting Workflow.
Replaces #778.
> docs(*): specify Helm v2.5.0 or later

- mkdocs.yml
- src/changelogs/v2.17.0.md
- src/installing-workflow/chart-provenance.md
- src/installing-workflow/index.md
- src/quickstart/install-cli-tools.md
- src/roadmap/releases.md
> docs(*): updates/changelog for v2.17.0 release

- README.md
Microsoft relicensed as MIT several months ago.
> docs(README.md): remove outdated license blurb
